# Generated by Django 5.0.7 on 2024-08-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_bascket',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
