# Generated by Django 5.0.7 on 2024-10-01 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_product_quantity_bascket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-order_id']},
        ),
    ]
